backend:
  name: git-gateway
  branch: main # ATENÇÃO: Se o seu repositório no GitHub usar 'master' em vez de 'main', altere esta palavra.

media_folder: "imagem" # Pasta onde o painel vai salvar as fotos que o funcionário subir
public_folder: "imagem"

collections:
  - name: "catalogo"
    label: "Gerenciar Catálogo"
    editor:
      preview: false
    files:
      - label: "Lista de Decorações"
        name: "decoracoes"
        file: "dados/decoracoes.json"
        fields:
          - label: "Minhas Decorações"
            name: "itens"
            widget: "list"
            fields:
              - {label: "Nome do Tema", name: "titulo", widget: "string"}
              - {label: "Prioridade (Ex: 1 para topo. Deixe em branco p/ normal)", name: "rank", widget: "number", required: false}
              - {label: "Preço Básico (R$)", name: "precoB", widget: "string"}
              - {label: "Foto Básico", name: "imgB", widget: "image"}
              - {label: "Preço Standard (R$)", name: "precoS", widget: "string"}
              - {label: "Foto Standard", name: "imgS", widget: "image"}
              - {label: "Preço Premium (R$)", name: "precoP", widget: "string"}
              - {label: "Foto Premium", name: "imgP", widget: "image"}