backend:
  name: git-gateway
  branch: main

media_folder: "imagem"
public_folder: "imagem"

collections:
  - name: "catalogo"
    label: "Gerenciar Catálogo"
    editor:
      preview: false
    files:
      - label: "Lista de Decorações"
        name: "decoracoes"
        file: "dados/decoracoes.json"
        fields:
          - label: "Minhas Decorações"
            name: "itens"
            widget: "list"
            fields:
              - {label: "Nome do Tema", name: "titulo", widget: "string"}
              - label: "Prioridade na Vitrine"
                name: "rank"
                widget: "select"
                options:
                  - { label: "Alta (Fica no topo)", value: "-10" }
                  - { label: "Média (Fica no meio)", value: "0" }
                  - { label: "Baixa (Fica por último)", value: "10" }
                default: "0"
              - {label: "Foto Básico", name: "imgB", widget: "image"}
              - {label: "Foto Standard", name: "imgS", widget: "image"}
              - {label: "Foto Premium", name: "imgP", widget: "image"}